# Generated by Django 4.0.5 on 2022-09-12 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0013_comment_article_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ManyToManyField(related_name='article', to=settings.AUTH_USER_MODEL),
        ),
    ]
